# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 21:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name=b'Service Category Name')),
                ('description', models.TextField(verbose_name=b'Service Category Description')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField(verbose_name=b'text_comment')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name=b'Job Name')),
                ('client_organization', models.TextField(max_length=256, verbose_name=b'What organization do you represent?')),
                ('description', models.TextField(max_length=256, verbose_name=b'Job Description')),
                ('deliverable', models.TextField(max_length=256, verbose_name=b'Deliverable')),
                ('duedate', models.DateTimeField(verbose_name=b'Date Due')),
                ('stakeholders', models.TextField(verbose_name=b'Stakeholders')),
                ('tech_specs', models.TextField(blank=True, verbose_name=b'Technical Specifications')),
                ('budget', models.TextField(verbose_name=b'Budget')),
                ('attachments', models.FileField(blank=True, upload_to=b'job')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_job', 'Can view Job'), ('edit_job', 'Can edit Job'), ('is_creator', 'Is a creator of Job')),
            },
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.NullBooleanField(default=False)),
                ('declined', models.NullBooleanField(default=False)),
                ('completed', models.NullBooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobrequests', to='dbtest.Job')),
            ],
            options={
                'permissions': (('view_jobrequest', 'Can view JobRequest'), ('edit_jobrequest', 'Can edit JobRequest'), ('edit_jobrequest_state', 'Can edit JobRequest state')),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, verbose_name=b'Organization Name')),
                ('description', models.TextField(verbose_name=b'Organization Description')),
                ('email', models.CharField(max_length=64, null=True, verbose_name=b'Organization email')),
                ('phone_number', models.CharField(max_length=64, null=True, verbose_name=b'Organization phone number')),
                ('icon', models.ImageField(null=True, upload_to=b'organization')),
                ('available', models.BooleanField(choices=[(True, b'Accepting Jobs'), (False, b'Not accepting Jobs')], default=True)),
                ('categories', models.ManyToManyField(to='dbtest.Category')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'permissions': (('view_organization', 'Can view Organization'), ('edit_organization', 'Can edit Organization'), ('is_admin', 'Is an Administrator')),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name=b'Username')),
                ('purdueuser', models.BooleanField(default=True)),
                ('visited_views', models.CharField(default=b'', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtest.Organization'),
        ),
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.ManyToManyField(through='dbtest.JobRequest', to='dbtest.Organization'),
        ),
        migrations.AddField(
            model_name='comment',
            name='jobrequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtest.JobRequest'),
        ),
    ]
