# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0004_auto_20160201_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='client_organization',
            field=models.TextField(max_length=256, verbose_name=b'What organization do you represent?'),
        ),
    ]
