# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0005_auto_20160201_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='categories',
        ),
        migrations.AlterField(
            model_name='organization',
            name='icon',
            field=models.ImageField(null=True, upload_to=b'organization'),
        ),
    ]
