# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0006_auto_20160220_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'permissions': (('view_jobrequest', 'Can view JobRequest'), ('edit_jobrequest', 'Can edit JobRequest'), ('edit_jobrequest_state', 'Can edit JobRequest state'))},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_views',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='available',
            field=models.BooleanField(choices=[(True, b'Accepting Jobs'), (False, b'Not accepting Jobs')], default=True),
        ),
    ]
