# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtest', '0007_auto_20160221_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='visited_views',
            field=models.CharField(default=b'', max_length=64),
        ),
    ]
